-- Create table for intermediate milestones
CREATE TABLE IF NOT EXISTS public.loyalty_milestones (
    id bigint generated by default as identity primary key,
    stamps_required int NOT NULL,
    reward_name text NOT NULL,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.loyalty_milestones ENABLE ROW LEVEL SECURITY;

-- Policy 1: Public Read
CREATE POLICY "Public milestones read access" ON public.loyalty_milestones
    FOR SELECT USING (true);

-- Policy 2: Admin Update/Insert/Delete
CREATE POLICY "Admins can manage milestones" ON public.loyalty_milestones
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Grant permissions
GRANT SELECT ON public.loyalty_milestones TO anon, authenticated;
GRANT ALL ON public.loyalty_milestones TO authenticated;
